I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script
    $ a = "test1"
  File "game/script.rpy", line 25, in script
    $ a = "test1"
  File "game/script.rpy", line 25, in <module>
    $ a = "test1"
NameError: name 'test1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 25, in script
    $ a = "test1"
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 25, in script
    $ a = "test1"
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 25, in <module>
    $ a = "test1"
NameError: name 'test1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
test 1.0
Mon Dec 16 13:48:25 2024
