I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 914, in script call
    call lifecount2
  File "game/script.rpy", line 1343, in script
    if life_counter1 == 3:
  File "game/script.rpy", line 1343, in <module>
    if life_counter1 == 3:
NameError: name 'life_counter1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 914, in script call
    call lifecount2
  File "game/script.rpy", line 1343, in script
    if life_counter1 == 3:
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Erik\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1343, in <module>
    if life_counter1 == 3:
NameError: name 'life_counter1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Heapsort 1.0
Thu Dec  5 06:07:39 2024
